- package.json
- recipes/RoutingHashHalogen/README.md
- recipes/RoutingHashLog/README.md
- recipes/RoutingPushHalogen/README.md
- recipes/Template/README.md
> Remove need to use `cookbook:` prefix when specifying recipe

- README.md
Fixes #8 
If this "contributing a new recipe" section gets too big or should appear in a CONTRIBUTING.md file, we can do that later.
> Add note about not adding/overriding packages in `packages.dhall` file.

- package.json
#16 passed because it just used the `Template` placeholder in the config. If you run `npm run serve --recipe=RoutingHashLog` it actually launches the `Template`.
This PR changes the placeholder so it fails instead.
Unfortunately, the npm logs in the failing case are not helpful since the variables are not expanded. (see https://github.com/npm/cli/issues/1417). Users would get a better clue to what's wrong if the logs were like this:
```
> parcel recipes/RecipeNameMissing/dev/index.html --out-dir recipes/RecipeNameMissing/dev-dist --open
```
But instead we just get this:
```
npm run serve --recipe=RoutingHashLog
> @ serve /home/miles/projects/purescript/cookbook
> parcel recipes/$npm_package_config_recipe/dev/index.html --out-dir recipes/$npm_package_config_recipe/dev-dist --open
Server …
```
> Fail if config not set correctly

- package.json
- recipes/RoutingHashHalogen/README.md
- recipes/RoutingHashLog/README.md
- recipes/RoutingPushHalogen/README.md
- recipes/Template/README.md
This reverts commit cd9193a1bd0f53bd48dabfc05e7dca3b2bb1c360.
This should go in after #25 
We could also change `cookbook` to `cb` or something.
> Revert "Remove need to use `cookbook:` prefix when specifying recipe"

- README.md
`prelude` is implied, and doesn't need to be explicitly listed in `spago.dhall`.
I'm wondering if `console` and `effect` are worth listing either. It makes this list pretty busy. Maybe we should just list additions beyond what's available by default after `spago init`.
> Edit packages in table

- .travis.yml
We don't currently run the full build command when recipes use `parcel`. This fixes that.
> Run `make buildAllDev` when running CI to build all recipes

- .travis.yml
Resolves #39.
Figured this is worth a try. We can revert it later if it's not working out.
Regarding your earlier request to use repo branches for PRs for easier edits, I don't think that's necessary with the default "Allow edits by maintainers" settings.
~~Try adding a newline on line 12 `.travis.yml` for this PR.~~
Edit: Give this a shot with a file on the next PR. I'm going to merge this now to check if caching works.
> Cache output directory

- makefile
> Use `>` instead of tab characte for listing steps in a make command

- .travis.yml
- makefile
Fixes #14
Fixes #10
Current issue: `%-buildProd` fails to build because [`make` thinks `HelloWorld/prod/index.html` is a recipe name](https://travis-ci.com/github/JordanMartinez/purescript-cookbook/builds/172322362#L339). I'm not entirely sure why...
> Use .ONESHELL and run recipes' CI based on backend compatibility

- makefile
Fixes #64 
Interesting makefile behavior with this one.
Shortest stem takes priority... except when:
> a rule whose prerequisites actually exist or are mentioned always takes priority over a rule with prerequisites that must be made by chaining other implicit rules.
And **zero prerequisites** for `recipes/%:` is interpreted as prerequisites that "actually exist or are mentioned".
> fix %-buildProd target

- recipes/ReadPrintFileContents/README.md
- recipes/ReadPrintFileContents/src/Main.purs
One of the types of CI errors we'll encounter are readme diffs.
Printing a different file during this test helps with visual inspection of the CI logs.
> ReadPrintFileContents - show license instead of readme

- README.md
- recipes/TextFieldsHalogen/.gitignore
- recipes/TextFieldsHalogen/README.md
- recipes/TextFieldsHalogen/spago.dhall
- recipes/TextFieldsHalogen/src/Main.purs
- recipes/TextFieldsHalogen/web/index.html
- recipes/TextFieldsHalogen/web/index.js
Addresses part of #86.
**DO NOT MERGE** - Can't finish until we have a `reverse :: String -> String` function in the package set. We could add it here, but that seems somewhat ridiculous for a simple function like this. (Granted, I realize reversing a string isn't simple due to encoding-related issues).
> Add text fields halogen

- .github/ISSUE_TEMPLATE/recipe-request.md
I feel like a simpler recipe request form will make this repo more inviting.
We can always add more requirements if we notice a pattern of missing content in recipe requests.
> Cut down on recipe request paperwork

- makefile
Compiling the PS code for all recipes seems to help with the VSCode IDE when editing, although there are still some additional configurations to sort-out for dealing with this non-traditional workspace.
> add buildAll command

- README.md
- recipes/DebuggingLog/.gitignore
- recipes/DebuggingLog/README.md
- recipes/DebuggingLog/nodeSupported.md
- recipes/DebuggingLog/spago.dhall
- recipes/DebuggingLog/src/Main.purs
- recipes/DebuggingLog/web/index.html
- recipes/DebuggingLog/web/index.js
Fixes #116 
This doesn't cover `trace` yet, though it should. Please give feedback.
> Add DebuggingLog

- recipes/BookReactHooks/src/Main.purs
This is a great resource, thanks for starting it!
I think for simple "fetch and display" tasks it's better to use `useAff`'s result directly rather than synchronizing it with a separate state. Do you prefer the separate state type? (this is mostly for my curiosity, with the PR just providing a diff to look at -- feel free to ignore/close).
> Use useAff's result instead of synchronizing with separate state

- CONTRIBUTING.md
- README.md
- makefile
- scripts/ReadmeContent.md
- scripts/newRecipe.sh
> Add newRecipe script

- README.md
- recipes/MemoizeFibonacci/.gitignore
- recipes/MemoizeFibonacci/README.md
- recipes/MemoizeFibonacci/nodeSupported.md
- recipes/MemoizeFibonacci/spago.dhall
- recipes/MemoizeFibonacci/src/Main.purs
- recipes/MemoizeFibonacci/web/index.html
- recipes/MemoizeFibonacci/web/index.js
> Memoize fibonacci

- recipes/BookReactHooks/src/Main.purs
- recipes/ButtonsReactHooks/src/Main.purs
- recipes/CardsReactHooks/src/Main.purs
- recipes/CatGifsReactHooks/src/Main.purs
- recipes/ClockReactHooks/src/Main.purs
- recipes/FormsReactHooks/src/Main.purs
- recipes/GroceriesReactHooks/src/Main.purs
- recipes/HelloReactHooks/src/Main.purs
- recipes/NumbersReactHooks/src/Main.purs
- recipes/PositionsReactHooks/src/Main.purs
- recipes/TextFieldsReactHooks/src/Main.purs
- recipes/TimeReactHooks/src/Main.purs
Fixes #196 
I you open the dev console, you'll find this warning from `react-dom.development.js`
> Warning: render(): Rendering components directly into document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try rendering into a container element created for your app.
But this is the same as what Halogen does, so I don't think we need to be concerned.
> Make react recipes compatible with try-purescript

- recipes/SignalSnakeJs/src/Main.purs
The previous approach with `setAttribute` was not very type safe.
> Set canvas dimensions without strings

- recipes/GroceriesHalogenHooks/src/Main.purs
- recipes/GroceriesReactHooks/src/Main.purs
Intended to be merged after #210 
For larger apps, it's good to prefix the HTML tags, but in this case, I don't want newcomers comparing these examples to Elm and concluding that PS syntax is terrible.
> Reduce groceries verbosity

- scripts/newRecipe.sh
There are portability issues with in-place substitution (`-i`) between the GNU (most linux distros) and BSD (mac osx) versions of `sed`.
See https://stackoverflow.com/a/21243111 for details.
> portable sed replacement when creating new recipes

- recipes/DragAndDropReactHooks/src/Main.purs
I thought I could get away with just setting `hover` in `onDragEnter` and `onDragLeave`, but turns out [`onDragLeave` is triggered when cursor moves to a child element](https://stackoverflow.com/questions/7110353/html5-dragleave-fired-when-hovering-a-child-element).
> Fix DragAndDropReactHooks set hover to true in onDragOver

- shell.nix
`packages.dhall` specifies PureScript 0.13.8, while the `easy-purescript-nix` commit hash points to 0.13.6, so trying to build the project in `nix-shell` fails.
> Bump `easy-purescript-nix`

- package.json
- recipes/DragAndDropReactHooks/src/Main.purs
Slight refactor to get rid of the homespun `toDragEvent` here and remove the usage of `Unsafe.Coerce.coerce`. I wasn't aware of `React.Basic.DOM.Events.nativeEvent` at the time.
> Remove unnecessary Unsafe.Coerce usage

- recipes/CatGifsReactHooks/src/Main.purs
CatGifsReactHook was trying to extract a gif url that does not match the latest giphy respones. 
Updated the getRandomCatGif function to work with latest giphy API
> chore: giphy cat api has updated, updating CatGifsReactHook to match

- package.json
- packages.dhall
- recipes/HelloReactHooks/spago.dhall
- recipes/HelloReactHooks/src/Main.purs
This is the suggested update path to react v18:
* Rendering into `#root` (solves Solves https://github.com/JordanMartinez/purescript-cookbook/issues/198)
* Using `createRoot` as recommented in react v18
* Rename component to generic name (`app`), for consistency across examples.
If this change is good to go, I can roll it out to all `ReactHooks` examples.
```
./BookReactHooks/
./ButtonsReactHooks/
./CardsReactHooks/
./CatGifsReactHooks/
./ClockReactHooks/
./ComponentsInputReactHooks/
./ComponentsMultiTypeReactHooks/
./ComponentsReactHooks/
./DragAndDropReactHooks/
./FileUploadReactHooks/
./FormsReactHooks/
./GroceriesReactHooks/
./HelloReactHooks/
./ImagePreviewsReactHooks/
./NumbersReactHooks/
./PositionsReactHooks/
./RoutingHashReactHooks/
./RoutingPushReactHooks/
./ShapesReactHooks/ …
```
> React v18 update

- .github/workflows/tests.yml
Seeing the following error in the CI build for #304 
```
=== Building HelloLog for the web browser backend ===
/home/runner/work/purescript-cookbook/purescript-cookbook/node_modules/@parcel/utils/lib/index.js:37573
#getIndex(item) {
^
SyntaxError: Unexpected token '('
```
`#getIndex` is using relatively new [private class field](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) syntax. According to MDN, that should be valid in Node v12 so I'm not sure why this is failing with a syntax error. Trying to bump to v18 to see if that helps.
> CI: Bump Node version to latest LTS
