JordanMartinez/purescript-cookbook

.github/ISSUE_TEMPLATE/recipe-request.md
README.md

Update new recipe requests to include module/folder name proposal

---

.github/ISSUE_TEMPLATE/meta-issue.md

Also figured it would be nice to make this more freeform rather than duplicate the recipe sections

Change `meta issue` to `cookbook issue`

---

.travis.yml

Wanted to see if this works too on main repo

Try simpler travis

---

makefile

**Edit by Jordan:** Partially addresses #24 
Here's one makefile approach.
There are some options for command format. Currently using the first one:
* `make Template-run`
* `make runTemplate`
* etc...

Add makefile that uses pattern matching strategy

---

README.md

Instructions should probably come first.
We can point folks to "Principles" (maybe rename this to "Additional Guidelines") if there are PR issues.

Feature Instructions before Principles

---

CONTRIBUTING.md
README.md

Follow up from #30 
Also fixes #29

Port new recipe instructions to Contributing; use ReadMe for recipe list

---

recipes/HelloWorld/dev/index.js
recipes/RoutingHashHalogen/dev/index.js
recipes/RoutingHashLog/dev/index.js
recipes/RoutingPushHalogen/dev/index.js

Add "use strict"; to `dev/index.js` files

---

CONTRIBUTING.md

Add note that all recipes are licensed under MIT; clarify isues

---

recipes/HelloWorld/README.md
recipes/RoutingHashHalogen/README.md
recipes/RoutingHashLog/README.md
recipes/RoutingPushHalogen/README.md

Restored some notes about what to expect that were lost in #40
@JordanMartinez Check if the "Allow edits by maintainers" setting is working for you with this PR.

Add note about expected behavior in recipe readmes

---

makefile

Change `run` and `serve` targets to `node` and `browser` respectively

---

CONTRIBUTING.md
README.md
RecipeTable.md
makefile
recipes/HelloWorld/nodeSupported.md
recipes/RoutingHashLog/nodeSupported.md
scripts/ReadmeContent.md
scripts/generateRecipeTable.sh

Add script to automatically generate table of recipes

---

makefile

Add shell and make flags

---

.travis.yml
recipes/HelloWorld/README.md

Check if recipe table was properly updated

---

CONTRIBUTING.md

Add a few resources on `make`; clarify why we used it over other tools

---

makefile

Really fixes #51 by fixing problems introduced by #52.

Set default shell to bash; add -c to shell flags

---

.travis.yml

Only build master branch and PRs targeting master branch

---

CONTRIBUTING.md

Update recipe instructions

---

CONTRIBUTING.md

Add constraint: all recipes using npm package foo must use same version of foo

---

.travis.yml
README.md
makefile
package.json
pnpm-lock.yaml
scripts/ReadmeContent.md

Swap package managers: npm -> pnpm

---

.github/ISSUE_TEMPLATE/recipe-request.md
CONTRIBUTING.md

While implementing #73, I cleaned up the below instructions

Cleanup recipe-adding instructions

---

README.md
package.json
pnpm-lock.yaml
recipes/BigInt/.gitignore
recipes/BigInt/README.md
recipes/BigInt/nodeSupported.md
recipes/BigInt/spago.dhall
recipes/BigInt/src/Main.purs
recipes/BigInt/web/index.html
recipes/BigInt/web/index.js

Add BigInt recipe

---

README.md
recipes/ReadPrintFileContents/.gitignore
recipes/ReadPrintFileContents/README.md
recipes/ReadPrintFileContents/nodeSupported.md
recipes/ReadPrintFileContents/spago.dhall
recipes/ReadPrintFileContents/src/Main.purs

Add ReadPrintFileContents

---

README.md
makefile
recipes/WindowProperties/.gitignore
recipes/WindowProperties/README.md
recipes/WindowProperties/spago.dhall
recipes/WindowProperties/src/Main.purs
recipes/WindowProperties/web/index.html
recipes/WindowProperties/web/index.js

Add window properties

---

scripts/build-all-dev.sh
scripts/build-all-prod.sh

These were from when we were experimenting with various tools for building and testing recipes

Remove old unused scripts

---

makefile

Simplify targetsAllCI

---

README.md
recipes/AddRemoveEventListener/.gitignore
recipes/AddRemoveEventListener/README.md
recipes/AddRemoveEventListener/spago.dhall
recipes/AddRemoveEventListener/src/Main.purs
recipes/AddRemoveEventListener/web/index.html
recipes/AddRemoveEventListener/web/index.js

Add AddRemoveEventListener

---

README.md
recipes/FindDomElement/.gitignore
recipes/FindDomElement/README.md
recipes/FindDomElement/spago.dhall
recipes/FindDomElement/src/Main.purs
recipes/FindDomElement/web/index.html
recipes/FindDomElement/web/index.js

Add FindDomElement recipe

---

README.md
recipes/HelloHalogen/.gitignore
recipes/HelloHalogen/README.md
recipes/HelloHalogen/spago.dhall
recipes/HelloHalogen/src/Main.purs
recipes/HelloHalogen/web/index.html
recipes/HelloHalogen/web/index.js

Add hello halogen

---

README.md
recipes/GroceriesHalogen/.gitignore
recipes/GroceriesHalogen/README.md
recipes/GroceriesHalogen/spago.dhall
recipes/GroceriesHalogen/src/Main.purs
recipes/GroceriesHalogen/web/index.html
recipes/GroceriesHalogen/web/index.js

Add groceries

---

README.md
recipes/ButtonsHalogen/.gitignore
recipes/ButtonsHalogen/README.md
recipes/ButtonsHalogen/spago.dhall
recipes/ButtonsHalogen/src/Main.purs
recipes/ButtonsHalogen/web/index.html
recipes/ButtonsHalogen/web/index.js

Add buttons halogen

---

README.md
recipes/NumbersHalogen/.gitignore
recipes/NumbersHalogen/README.md
recipes/NumbersHalogen/spago.dhall
recipes/NumbersHalogen/src/Main.purs
recipes/NumbersHalogen/web/index.html
recipes/NumbersHalogen/web/index.js

Add random halogen

---

README.md
recipes/CardsHalogen/.gitignore
recipes/CardsHalogen/README.md
recipes/CardsHalogen/spago.dhall
recipes/CardsHalogen/src/Main.purs
recipes/CardsHalogen/web/index.html
recipes/CardsHalogen/web/index.js

Add cards halogen

---

README.md
recipes/PositionsHalogen/.gitignore
recipes/PositionsHalogen/README.md
recipes/PositionsHalogen/spago.dhall
recipes/PositionsHalogen/src/Main.purs
recipes/PositionsHalogen/web/index.html
recipes/PositionsHalogen/web/index.js

Add positions halogen

---

makefile
recipes/TextFieldsHalogen/web/index.js

Split into three stages:
1. Demonstrate mismatch slipping through CI
1. Add code to catch mismatch in CI - Now caught on [this line](https://travis-ci.com/github/JordanMartinez/purescript-cookbook/builds/173787369#L416)
1. Fix original mismatch

Ensure index.js points to correct recipe

---

README.md
scripts/ReadmeContent.md

Show console snippets for running recipes

---

README.md
recipes/TimeHalogen/.gitignore
recipes/TimeHalogen/README.md
recipes/TimeHalogen/spago.dhall
recipes/TimeHalogen/src/Main.purs
recipes/TimeHalogen/web/index.html
recipes/TimeHalogen/web/index.js

Add time halogen

---

README.md
recipes/BookHalogen/.gitignore
recipes/BookHalogen/README.md
recipes/BookHalogen/spago.dhall
recipes/BookHalogen/src/Main.purs
recipes/BookHalogen/web/index.html
recipes/BookHalogen/web/index.js

Add book halogen

---

README.md
package.json
pnpm-lock.yaml
recipes/HelloReact/.gitignore
recipes/HelloReact/README.md
recipes/HelloReact/spago.dhall
recipes/HelloReact/src/Main.purs
recipes/HelloReact/web/index.html
recipes/HelloReact/web/index.js

Add HelloReact recipe

---

README.md
recipes/GroceriesReact/.gitignore
recipes/GroceriesReact/README.md
recipes/GroceriesReact/spago.dhall
recipes/GroceriesReact/src/Main.purs
recipes/GroceriesReact/web/index.html
recipes/GroceriesReact/web/index.js

Add GroceriesReact example

---

README.md
recipes/ButtonsReact/.gitignore
recipes/ButtonsReact/README.md
recipes/ButtonsReact/spago.dhall
recipes/ButtonsReact/src/Main.purs
recipes/ButtonsReact/web/index.html
recipes/ButtonsReact/web/index.js

Add ButtonsReact

---

README.md
recipes/TextFieldsReact/.gitignore
recipes/TextFieldsReact/README.md
recipes/TextFieldsReact/spago.dhall
recipes/TextFieldsReact/src/Main.purs
recipes/TextFieldsReact/web/index.html
recipes/TextFieldsReact/web/index.js

Add TextFieldsReact

---

recipes/RoutingPushHalogen/src/Example.purs
recipes/RoutingPushHalogen/src/Routing.purs

Also nice to include an example with query params and demonstrate that order doesn't matter.

RoutingPushHalogen - add query param example

---

README.md
recipes/NumbersReact/.gitignore
recipes/NumbersReact/README.md
recipes/NumbersReact/spago.dhall
recipes/NumbersReact/src/Main.purs
recipes/NumbersReact/web/index.html
recipes/NumbersReact/web/index.js

Add NumbersReact

---

README.md
recipes/PositionsReact/.gitignore
recipes/PositionsReact/README.md
recipes/PositionsReact/spago.dhall
recipes/PositionsReact/src/Main.purs
recipes/PositionsReact/web/index.html
recipes/PositionsReact/web/index.js

Add PositionsReact

---

README.md
package.json
pnpm-lock.yaml
recipes/CardsReact/.gitignore
recipes/CardsReact/README.md
recipes/CardsReact/spago.dhall
recipes/CardsReact/src/Main.purs
recipes/CardsReact/web/index.html
recipes/CardsReact/web/index.js

Add CardsReact

---

README.md
recipes/BookReact/.gitignore
recipes/BookReact/README.md
recipes/BookReact/spago.dhall
recipes/BookReact/src/Main.purs
recipes/BookReact/web/index.html
recipes/BookReact/web/index.js

Add BookReact

---

README.md
recipes/CatGifsReact/.gitignore
recipes/CatGifsReact/README.md
recipes/CatGifsReact/spago.dhall
recipes/CatGifsReact/src/Main.purs
recipes/CatGifsReact/web/index.html
recipes/CatGifsReact/web/index.js

Add CatGifsReact

---

README.md
recipes/CardsHalogen/README.md
recipes/CardsHalogen/spago.dhall
recipes/CardsHalogen/src/Main.purs
recipes/CardsReact/README.md
recipes/CardsReact/src/Main.purs

Update Halogen and React cards recipes

---

README.md
scripts/ReadmeContent.md
shell.nix

- readme install information
- How to remove spago, purescript dependencies with 1 line
command. (unix only)
- create pinned purs 0.13.6 dependencies with spago and the rest. shell.nix
Let me know if you want to pin higher version of the purs, I picked 0.13.6 because I saw that in packages.dhall

add info for Nix-users to install dependencies.

---

README.md
recipes/FileUploadHalogenHooks/.gitignore
recipes/FileUploadHalogenHooks/README.md
recipes/FileUploadHalogenHooks/spago.dhall
recipes/FileUploadHalogenHooks/src/Main.purs
recipes/FileUploadHalogenHooks/web/index.html
recipes/FileUploadHalogenHooks/web/index.js

Add FileUploadHalogenHooks

---

README.md
recipes/DragAndDropHalogenHooks/.gitignore
recipes/DragAndDropHalogenHooks/README.md
recipes/DragAndDropHalogenHooks/spago.dhall
recipes/DragAndDropHalogenHooks/src/Main.purs
recipes/DragAndDropHalogenHooks/web/index.css
recipes/DragAndDropHalogenHooks/web/index.html
recipes/DragAndDropHalogenHooks/web/index.js

Addresses part of #86
This one took a while to figure out because Elm is doing some unsafe things behind the scenes. I decided to use a different approach.

Add DragAndDropHalogenHooks

---

README.md
recipes/ImagePreviewsHalogenHooks/.gitignore
recipes/ImagePreviewsHalogenHooks/README.md
recipes/ImagePreviewsHalogenHooks/spago.dhall
recipes/ImagePreviewsHalogenHooks/src/Main.purs
recipes/ImagePreviewsHalogenHooks/web/index.css
recipes/ImagePreviewsHalogenHooks/web/index.html
recipes/ImagePreviewsHalogenHooks/web/index.js

Add ImagePreviesHalogenHooks

---

recipes/DragAndDropHalogenHooks/src/Main.purs

Fixes compiler warnings introduced in #152

Remove unused imports to fix compiler warning

---

CONTRIBUTING.md
broken/README.md

Minor admin work we didn't get to yet.

Add broken folder's readme

---

recipes/DragAndDropHalogenHooks/src/Main.purs
recipes/DragAndDropHalogenHooks/web/index.css

Original:
```
label
div (button style)
input
span
```
New:
```
label (button style)
input
span
```

DragDropHalogen - Simplify input in label

---

README.md
recipes/FormsReactHooks/.gitignore
recipes/FormsReactHooks/README.md
recipes/FormsReactHooks/spago.dhall
recipes/FormsReactHooks/src/Main.purs
recipes/FormsReactHooks/web/index.html
recipes/FormsReactHooks/web/index.js

Add FormsReactHooks

---

README.md
recipes/TimeReactHooks/.gitignore
recipes/TimeReactHooks/README.md
recipes/TimeReactHooks/spago.dhall
recipes/TimeReactHooks/src/Main.purs
recipes/TimeReactHooks/web/index.html
recipes/TimeReactHooks/web/index.js

Add TimeReactHooks

---

README.md
recipes/HelloConcur/.gitignore
recipes/HelloConcur/README.md
recipes/HelloConcur/spago.dhall
recipes/HelloConcur/src/Main.purs
recipes/HelloConcur/web/index.html
recipes/HelloConcur/web/index.js

I have ported the simplest receipt to Concur; if the result is suitable for inclusion in the cookbook, I will keep on porting the other receipts.

Implementation of the HelloWorld receipt using Concur

---

README.md
recipes/WriteFileNode/.gitignore
recipes/WriteFileNode/README.md
recipes/WriteFileNode/example.txt
recipes/WriteFileNode/nodeSupported.md
recipes/WriteFileNode/spago.dhall
recipes/WriteFileNode/src/Main.purs

Add WriteFileNode

---

README.md
recipes/BasicHalogenHooks/.gitignore
recipes/BasicHalogenHooks/README.md
recipes/BasicHalogenHooks/spago.dhall
recipes/BasicHalogenHooks/src/Main.purs
recipes/BasicHalogenHooks/web/index.html
recipes/BasicHalogenHooks/web/index.js

Add BasicHalogenHooks

---

README.md
recipes/ComponentsHalogenHooks/.gitignore
recipes/ComponentsHalogenHooks/README.md
recipes/ComponentsHalogenHooks/spago.dhall
recipes/ComponentsHalogenHooks/src/Main.purs
recipes/ComponentsHalogenHooks/web/index.html
recipes/ComponentsHalogenHooks/web/index.js

Add ComponentsHalogenHooks

---

recipes/TimeHalogenHooks/spago.dhall
recipes/TimeHalogenHooks/src/Main.purs
recipes/TimeReactHooks/spago.dhall
recipes/TimeReactHooks/src/Main.purs

Show local time in Time* examples

---

README.md
recipes/HeterogenousArrayLog/.gitignore
recipes/HeterogenousArrayLog/README.md
recipes/HeterogenousArrayLog/nodeSupported.md
recipes/HeterogenousArrayLog/spago.dhall
recipes/HeterogenousArrayLog/src/Main.purs
recipes/HeterogenousArrayLog/web/index.html
recipes/HeterogenousArrayLog/web/index.js

Add HeterogenousArrayLog

---

README.md
recipes/ClockReactHooks/.gitignore
recipes/ClockReactHooks/README.md
recipes/ClockReactHooks/spago.dhall
recipes/ClockReactHooks/src/Main.purs
recipes/ClockReactHooks/web/index.html
recipes/ClockReactHooks/web/index.js

Add ClockReactHooks recipe

---

README.md
recipes/DateTimeBasicsLog/.gitignore
recipes/DateTimeBasicsLog/README.md
recipes/DateTimeBasicsLog/nodeSupported.md
recipes/DateTimeBasicsLog/spago.dhall
recipes/DateTimeBasicsLog/src/Main.purs
recipes/DateTimeBasicsLog/web/index.html
recipes/DateTimeBasicsLog/web/index.js

Implement DateTimeBasicsLog

---

CONTRIBUTING.md

Follow-up to https://github.com/JordanMartinez/purescript-cookbook/issues/225#issuecomment-680469009

Convert template suggestions to table and other contributing edits

---

recipes/CatGifsHalogenHooks/src/Main.purs

Fixes #289 
giphy api updated. 
Recipe needs an update to its decoder.

chore: CatGifsHalogenHooks update json decode logic to match giphy api
